/*** Compiler Front-End Test automatically generated by the BNF Converter ***/
/*                                                                          */
/* This test will parse a file, print the abstract syntax tree, and then    */
/* pretty-print the result.                                                 */
/*                                                                          */
/****************************************************************************/
#include <stdio.h>
#include "Parser.h"
#include "Printer.h"
#include "Absyn.h"
#include "JVMInstructionsVisitor.h"

int main(int argc, char ** argv)
{
  FILE *input;
  if (argc > 1) 
  {
    input = fopen(argv[1], "r");
    if (!input)
    {
      fprintf(stderr, "Error opening input file.\n");
      exit(1);
    }
  }
  else input = stdin;
  /* The default entry point is used. For other options see Parser.H */
  ListStmt *parse_tree = pListStmt(input);
  if (parse_tree)
  {
    JVMInstructionsVisitor instructions_visitor;
    instructions_visitor.visitListStmt(parse_tree);

    return 0;
  }
  return 1;
}

